[package]
authors = ["adelille <adelile@42.student.fr>"]
edition = "2024"
name = "cloud-1_frontend"
publish = false
version = "0.2.0"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.7.7", features = ["csr"] }
